### ISSUE TITLE
[Bug]Not all content can be displayed on a smaller resolution monitor

### ISSUE THREAD

**Issue by mzwing** [Cyberhan123/stable-diffusion-desktop#15]
Like this:

![image](https://github.com/Cyberhan123/stable-diffusion-desktop/assets/69132261/0b97bf35-fa95-4b43-a68f-c3974d316ad6)

I can neither click the title bar nor see the upside button.

**Comment by Cyberhan123** [comment]
Do you have time to help me adjust the compatibility issue? I don’t use a computer of this size here.

**Comment by mzwing** [comment]
> Do you have time to help me adjust the compatibility issue? I don’t use a computer of this size here.

OK. How can I contact you?

**Comment by Cyberhan123** [comment]
https://github.com/Cyberhan123/stable-diffusion-desktop/blob/39da1b4863879788bc71e59a39262f8809a85c04/main.go#L21

You can modify the code here in the main program to adjust the height, but you need to pay attention to css style issues.

**Comment by Cyberhan123** [comment]
@mzwing  PR is welcome

**Comment by Cyberhan123** [comment]
If you want to contact me, you can add me as a WeChat friend. The mobile phone number is also WeChat ID: 15998628293

**Comment by mzwing** [comment]
> https://github.com/Cyberhan123/stable-diffusion-desktop/blob/39da1b4863879788bc71e59a39262f8809a85c04/main.go#L21
> 
> You can modify the code here in the main program to adjust the height, but you need to pay attention to css style issues.

Sounds like you didn't use the flexible css layout? (

> PR is welcome

I will have a try... But I don't have many spare time to do this since I still have to deal with the annoying study : (

One idea is to switch to full screen if the resolution is too small (like mine) (?

Maybe we can discuss it later (

> If you want to contact me, you can add me as a WeChat friend. The mobile phone number is also WeChat ID: 15998628293

OK, I will contact you after I come back home from school on Saturday afternoon (

**Comment by mzwing** [comment]
When I try to fix this, I encountered with this problem:

```pwsh
PS F:\repos\mzwing\stable-diffusion-desktop\frontend> wails build
Wails CLI v2.8.0


  ERROR   open F:\repos\mzwing\stable-diffusion-desktop\frontend\wails.json: The system cannot find the file specified.
 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

How can I fix it? I didn't use wails before.

**Comment by mzwing** [comment]
> @Cyberhan123
> 
> When I try to fix this, I encountered with this problem:
> 
> ```powershell
> PS F:\repos\mzwing\stable-diffusion-desktop\frontend> wails build
> Wails CLI v2.8.0
> 
> 
>   ERROR   open F:\repos\mzwing\stable-diffusion-desktop\frontend\wails.json: The system cannot find the file specified.
>  ♥   If Wails is useful to you or your company, please consider sponsoring the project:
> https://github.com/sponsors/leaanthony
> ```
> 
> How can I fix it? I didn't use wails before.

Fine. That seems to be a temporal problem.
