### ISSUE TITLE
Can it be used on Linux?

### ISSUE THREAD

**Issue by mzwing** [Cyberhan123/stable-diffusion-desktop#16]
As the title said.

I didn't see Linux related code after taking a cursory look at the code.

Can you give me the compile commands on Linux if it is available on Linux?

**Comment by Cyberhan123** [comment]
In release you can see the build products, the first one is.
compile commands：
https://wails.io/docs/gettingstarted/building

**Comment by mzwing** [comment]
> In release you can see the build products, the first one is. compile commands： https://wails.io/docs/gettingstarted/building

Oh, thx!
