### ISSUE TITLE
The app doesn't use all threads of CPU.

### ISSUE THREAD

**Issue by JohnClaw** [Cyberhan123/stable-diffusion-desktop#8]
And that makes it work much slower than cli sd.cpp.exe. You should probably add an option that will make possible to manually select amount of cpu threads used by your app.

**Comment by Cyberhan123** [comment]
Ok, This is easy to solve. I will add logic and try to use golang to get the number of cores. Then I will add this logic in the settings.

**Comment by Cyberhan123** [comment]
@JohnClaw  This is a work in progress, I think everything will be there, it just takes some time
<img width="1039" alt="截屏2024-01-09 00 00 30" src="https://github.com/Cyberhan123/stable-diffusion-desktop/assets/38837039/6a1c3721-6de8-4bbe-b223-3284ab04473f">

**Comment by Amin456789** [comment]
beautiful! thanks for ur hard work

**Comment by Cyberhan123** [comment]
@JohnClaw @Amin456789 try latest version

**Comment by Amin456789** [comment]
also could u please add a preset save 
i mean the setting we can save so we don't need to always choose models and setting changes we made, we can load it from there

**Comment by JohnClaw** [comment]
> try latest version

Thanks. Now it works as fast as my own SD.cpp GUI)) 
![image](https://github.com/Cyberhan123/stable-diffusion-desktop/assets/131554379/00ec564b-bf6b-4e4d-ac66-6b193c511a83)

However my GUI have some advantages: 1. It can process many images. Your GUI can process only one image. If i press Generate button second time, your GUI closes. 2. My GUI has progress bar. 3. My GUI is smaller: 2,76 Mb Your GUI: 19 Mb 4. My GUI is written in twinBasic, it's a simple language. Every one will be able to edit it and add new features, when i share the code. 5. My GUI doesn't show CMD window on start. Your does, here's the prove:
![image](https://github.com/Cyberhan123/stable-diffusion-desktop/assets/131554379/44db85be-eecb-42d0-82dc-2a0a3079aee0)

But i'm not a coder (and you possibly are), so your App will be much better when you finish it. Good luck.

**Comment by Cyberhan123** [comment]
You mean the program will crash? I haven't tested it on windows yet
